// Generated by CoffeeScript 1.4.0
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

window.Search = (function(_super) {

  __extends(Search, _super);

  function Search(options, livelist) {
    this.handleSearchFormSubmit = __bind(this.handleSearchFormSubmit, this);

    var _this = this;
    this.livelist = livelist;
    this.setOptions(options);
    $(this.formSelector).submit(function(event) {
      return _this.handleSearchFormSubmit(event);
    });
  }

  Search.prototype.searchTerm = function() {
    var q;
    q = $(this.searchTextInputSelector).val();
    if (!q || (q === '')) {
      return null;
    } else {
      return q;
    }
  };

  Search.prototype.handleSearchFormSubmit = function(event) {
    event.preventDefault();
    return $(this.livelist.listSelector).trigger(this.livelist.eventName);
  };

  return Search;

})(Utilities);
