// Generated by CoffeeScript 1.4.0
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

window.Utilities = (function() {

  function Utilities() {
    this.setOptions = __bind(this.setOptions, this);

  }

  Utilities.prototype.setOptions = function(options, context) {
    var _this = this;
    if (context == null) {
      context = this;
    }
    return _.each(options, function(value, option) {
      return context[option] = value;
    });
  };

  return Utilities;

})();
